CREATE DATABASE IF NOT EXISTS `tmt`;

USE `tmt`;

CREATE TABLE IF NOT EXISTS `User` (
    `UserID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Username` VARCHAR(30) NOT NULL,
    `Email` VARCHAR(100) NOT NULL,
    `Password` VARCHAR(60) NOT NULL
);